version: '3.9'

services:
  portainer:
    image: portainer/portainer-ce:latest

  eventcatalog.database:
    image: postgres:latest

  eventify.seq:
    image: datalust/seq:latest

  pgadmin:
    image: dpage/pgadmin4

  booking.redis:
    image: redis:latest

  eventcatalog.api:
    image: ${DOCKER_REGISTRY-}eventcatalogapi
    build:
      context: ../..
      dockerfile: Music/Eventify/EventCatalog/EventCatalog.Api/Dockerfile


  booking.api:
    image: ${DOCKER_REGISTRY-}bookingapi
    build:
      context: .
      dockerfile: Booking/Booking.Api/Dockerfile

volumes:
  portainer_data: